export const IPC_CHANNELS = {
  stateGet: "state:get",
  stateChanged: "state:changed",
  speechStatsGet: "speech-stats:get",
  appVersionGet: "app-version:get",
  settingsSave: "settings:save",
  settingsOpen: "settings:open",
  updatesGetState: "updates:get-state",
  updatesStateChanged: "updates:state-changed",
  updatesCheckManual: "updates:check-manual",
  updatesInstall: "updates:install",
  onboardingGet: "onboarding:get",
  onboardingUpdate: "onboarding:update",
  onboardingComplete: "onboarding:complete",
  onboardingReset: "onboarding:reset",
  onboardingVerificationGet: "onboarding-verification:get",
  onboardingVerificationChanged: "onboarding-verification:changed",
  onboardingVerificationArm: "onboarding-verification:arm",
  onboardingVerificationReset: "onboarding-verification:reset",
  modelsList: "models:list",
  modelDownload: "model:download",
  modelDownloadProgress: "model:download-progress",
  modelRemove: "model:remove",
  hotkeyCaptureStart: "hotkey:capture-start",
  hotkeyCaptureCancel: "hotkey:capture-cancel",
  hotkeyCaptured: "hotkey:captured",
  speechRuntimeDiagnostics: "speech-runtime:diagnostics",
  speechRuntimeInstall: "speech-runtime:install",
  permissionsOpenPrivacy: "permissions:open-privacy",
  permissionsRequestMicrophone: "permissions:request-microphone",
  permissionsCheck: "permissions:check",
  overlayUpdate: "overlay:update"
} as const;

export type IpcChannelName = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
